<!DOCTYPE z [
	<!ELEMENT z (a|(c,d)|e)*>
	<!ELEMENT a ((b,c,d)|(d,e,a*)|f+)>
	<!ELEMENT b ANY>
	<!ELEMENT c ((c*,((e,f)|g)*),b)>
	<!ELEMENT d (#PCDATA|d|z)*>
	<!ELEMENT e EMPTY>
	<!ELEMENT f (#PCDATA|a|c|d|e)*>
	<!ATTLIST a attr CDATA #REQUIRED
				attra CDATA #IMPLIED>
	<!ATTLIST b attr CDATA #REQUIRED>
]>

<z>
	<a attr="d" attra="c">
		<b attr="a">ciao</b>
		<c>
			<e/>
			<f>ciao</f>
			<b attr="aanc">
				qualsiasi
			</b>
		</c>
		<d>
			eccoci
		</d>
	</a>
</z>
