<!DOCTYPE CorsoDiLaurea [
	<!ELEMENT CorsoDiLaurea (Corso+)>
	<!ELEMENT Corso (NomeCorso, DescrizioneCorso?, Docente+, Studente*)>
	<!ELEMENT Docente (Cognome, Nome, Dipartimento, (Foto|Commento)*)>
	<!ELEMENT Studente (Cognome, Nome, (Foto|Commento)*)>
	<!ELEMENT NomeCorso (#PCDATA)>
	<!ELEMENT DescrizioneCorso (#PCDATA)>
	<!ELEMENT Cognome (#PCDATA)>
	<!ELEMENT Nome (#PCDATA)>
	<!ELEMENT Dipartimento (#PCDATA)>
	<!ELEMENT Foto EMPTY>
	<!ELEMENT Commento (#PCDATA)>
	<!ATTLIST CorsoDiLaurea
		facolta CDATA #REQUIRED>
	<!ATTLIST Corso
		numeroCrediti CDATA #REQUIRED
		semestre (primo|secondo|annuale) #REQUIRED
		sede CDATA #IMPLIED
		tipo (obbligatorio|opzionale) #IMPLIED >
	<!ATTLIST Studente
		matricola CDATA #REQUIRED>
	<!ATTLIST Foto
		url CDATA #REQUIRED>
]>

<CorsoDiLaurea facolta="Ingegneria informatica ed automatica">
	<Corso numeroCrediti="6" semestre="primo" sede="Roma" tipo="opzionale">
		<NomeCorso>Linguaggi e tecnologie per il web</NomeCorso>
		<DescrizioneCorso>Corso su analisi sintattica e traduzione guidata dalla sintassi,
		HTML, XML
		</DescrizioneCorso>
		<Docente>
			<Cognome>Rosati</Cognome>
			<Nome>Riccardo</Nome>
			<Dipartimento>DIS</Dipartimento>
			<Foto url="foto.jpg"/>
		</Docente>
		<Studente matricola="01234567">
			<Cognome>Trenta</Cognome>
			<Nome>Simone</Nome>
			<Commento>Fuori sede</Commento>
		</Studente>
	</Corso>
</CorsoDiLaurea>
