<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE a [
	<!ELEMENT a (b | c | d)*>
	<!ELEMENT b (#PCDATA)>
	<!ELEMENT c EMPTY>
	<!ELEMENT d (#PCDATA | a)*>
	<!ATTLIST a val CDATA #REQUIRED>
	<!ATTLIST b val CDATA #IMPLIED>
]>


<a val="v1">
	<b val="1">riga 1</b>
	<b val="pippo">riga 2</b>
	<c/>
	<b x="3">riga 3</b> <!--non esiste un attributo "x" per l'elemento b-->
	<d>riga 4
		<a val="v2">
			<c val="xyz"/> <!--non esiste un attributo "val" per l'elemento c-->
		</a>
	</d>
</a>
